/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  important: "#root",
  theme: {
    extend: {
      colors: {
        // Stitch 디자인 시스템 (Material You) 컬러 팔레트
        "on-tertiary":                "#fff6fd",
        "inverse-primary":            "#bbc7fd",
        "on-tertiary-fixed-variant":  "#634b72",
        "primary-container":          "#bbc7fd",
        "primary-fixed":              "#bbc7fd",
        "tertiary":                   "#6e567e",
        "secondary-container":        "#dee1f9",
        "on-primary-fixed-variant":   "#3d4976",
        "surface-container-lowest":   "#ffffff",
        "on-secondary-fixed":         "#3a3e51",
        "inverse-on-surface":         "#9d9ca2",
        "surface-variant":            "#e2e1ed",
        "surface-container":          "#eeedf6",
        "on-surface-variant":         "#5d5e68",
        "on-tertiary-fixed":          "#452f54",
        "outline-variant":            "#b1b1bc",
        "error-container":            "#f97386",
        "primary-fixed-dim":          "#adb9ee",
        "on-error-container":         "#6e0523",
        "on-secondary-container":     "#4d5164",
        "error-dim":                  "#6b0221",
        "inverse-surface":            "#0d0e12",
        "tertiary-container":         "#ebccfb",
        "primary-dim":                "#45517f",
        "on-secondary-fixed-variant": "#565b6f",
        "secondary-fixed-dim":        "#d0d3eb",
        "error":                      "#a8364b",
        "primary":                    "#515d8c",
        "on-background":              "#30323b",
        "outline":                    "#797a84",
        "secondary-fixed":            "#dee1f9",
        "on-primary-container":       "#33406d",
        "tertiary-fixed":             "#ebccfb",
        "surface-container-high":     "#e8e7f1",
        "surface-bright":             "#fbf8fe",
        "secondary":                  "#5a5e72",
        "secondary-dim":              "#4e5266",
        "tertiary-dim":               "#624a71",
        "surface-container-highest":  "#e2e1ed",
        "background":                 "#fbf8fe",
        "surface-container-low":      "#f4f2fb",
        "surface":                    "#fbf8fe",
        "on-error":                   "#fff7f7",
        "surface-dim":                "#d9d9e4",
        "on-surface":                 "#30323b",
        "surface-tint":               "#515d8c",
        "on-primary":                 "#faf8ff",
        "on-tertiary-container":      "#594268",
        "on-primary-fixed":           "#1f2b57",
        "tertiary-fixed-dim":         "#ddbfed",
        "on-secondary":               "#faf8ff",
        // 기존 brand 하위호환
        brand: {
          50:  "#f4f2fb",
          100: "#eeedf6",
          200: "#dee1f9",
          500: "#6b79a8",
          600: "#515d8c",
          700: "#3a4269",
        },
      },
      fontFamily: {
        sans:     ["Inter", "-apple-system", "BlinkMacSystemFont", "Segoe UI", "sans-serif"],
        headline: ["Plus Jakarta Sans", "sans-serif"],
        display:  ["Plus Jakarta Sans", "sans-serif"],
        body:     ["Inter", "sans-serif"],
        label:    ["Public Sans", "Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg:      "0.5rem",
        xl:      "0.75rem",
        "2xl":   "1rem",
        full:    "9999px",
      },
      keyframes: {
        "fade-in": {
          "0%":   { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "slide-down": {
          "0%":   { opacity: "0", transform: "translateY(-8px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-up": {
          "0%":   { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
      },
      animation: {
        "fade-in":    "fade-in 0.15s ease-out",
        "slide-down": "slide-down 0.2s cubic-bezier(0.16,1,0.3,1)",
        "fade-in-up": "fade-in-up 0.6s ease-out forwards",
      },
    },
  },
  plugins: [],
};
