spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME:passit_cs}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.company.cs: DEBUG
    org.springframework: DEBUG
    org.hibernate.SQL: DEBUG
